---

- hosts: xenial, bionic
  gather_facts: no
  become: True
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python


- hosts: all
  vars:
    onion_services:
      hsv2:
        onion_ports:
          - [22, 22]
        onion_version: 2
      hsv3:
        onion_ports:
          - [22, 22]
  roles:
    - ansible-role-onion
