---

- hosts: all
  vars:
    onion_services:
      ssh:
        onion_ports:
          - [22, 22]
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
  roles:
    - ansible-role-onion
