---
# handlers file for onion
- name: reload tor
  service:
    name: tor
    state: reloaded

- name: stop tor
  service:
    name: tor
    state: stopped

- name: restart monit
  service:
    name: monit
    state: restarted
