---
scenario:
  name: default
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: stretch64
    box: debian/stretch64
    memory: 512
    cpus: 1
  - name: jessie64
    box: debian/jessie64
    memory: 512
    cpus: 1
  - name: xenial64
    box: ubuntu/xenial64
    memory: 512
    cpus: 1
    provider_raw_config_args:
    - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
  - name: bionic64
    box: ubuntu/bionic64
    memory: 512
    cpus: 1
    provider_raw_config_args:
    - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
provisioner:
  name: ansible
  become: true
  lint:
    name: ansible-lint
    enabled: False
  playbooks:
    converge: playbook.yml
lint:
  name: yamllint
  enabled: True
verifier:
  name: goss
  lint:
    name: yamllint
